### PR TITLE
Changed layout button

### PR DESCRIPTION
**Pull request by TrueCoderSja**
image

### CODE REVIEW

**Comment by vishnurchityala** [comment]
Please share the GitHub pages link of your fork to see the function properly.

**Comment by TrueCoderSja** [comment]
Here it is: https://truecodersja.github.io/BU-Notes/pages/firstYear.html

**Comment by vishnurchityala** [comment]
You did a great work but i would suggest please fix CSS more that it looks more similar to the original component in G-Drive.

**Comment by vishnurchityala** [comment]
Raise new issue to fix the CSS i will assign that to you.

**Comment by TrueCoderSja** [comment]
Okay, sure. I'll be updating it shortly. So, I have to change the grid and tick icon or is there anything else?

**Comment by vishnurchityala** [comment]
Make the button similar to the g-drive component I attached in the issue.

**Comment by TrueCoderSja** [comment]
I have raised the issue. Please assign it to me.

**Pull request merged**
