### PR TITLE
changes made

### PR DESCRIPTION
**Pull request by Gyaanendra**
https://gyaanendra.github.io/BU-Notes/
the changes u asked have been made here also attaching a 
Img of how it looks on phone

### CODE REVIEW

**Comment by vishnurchityala** [comment]
Little more changes place search box adjacent to profile and tool box left to them. Give some right margin to profile they seem too close to the borders.

**Comment by vishnurchityala** [comment]
You doing Great 👏👏

**Comment by Gyaanendra** [comment]
Does the profile be adjacent to search only for the smaller device like phones or throughout any screen size

**Comment by vishnurchityala** [comment]
Search box and profile tool box should be together on top of content area in larger screens. and for smaller screens existing UI you made is good but give some y-padding.

**Comment by vishnurchityala** [comment]
image

**Comment by Gyaanendra** [comment]
Ok I will get back to you

**Comment by vishnurchityala** [comment]
Sure.. place profile icons bit above content area they seem too close to border of  webpage place them above of content area width.

**Pull request closed without merging**
